version : '3'

services:
    server:
        build: ./API
        expose:
            - ${APP_SERVER_PORT}
        environment: 
            API_HOST : ${API_HOST}
            APP_SERVER_PORT: ${APP_SERVER_PORT}
        ports: 
            - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
        volumes:
            - ./API/controllers:/srv/app/back/controllers
            - ./API/models:/srv/app/back/models
            - ./API/routes:/srv/app/back/routes
        command: npm run dev
    client:
        build: ./front/minsalud
        environment:
            - REACT_APP_PORT=${REACT_APP_PORT}
        expose: 
            - ${REACT_APP_PORT}
        ports: 
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - ./front/minsalud:/srv/app/front
        tty: true
        links:
            - server
        command: npm run start
        
