service: serverless-aws-nodejs
provider:
  name: aws #Define the cloud provider to use
  runtime: nodejs12.x 
  stage: dev
  region: sa-east-1
functions:
  app:
    handler: index.server 
    events: #Define the events that trigger the lambda
      - http: #Define an HTTP endpoint that respond to the / route
          path: / 
          method: ANY #Define the HTTP methods to be used (GET/POST)
          cors: true
      - http: #Define an HTTP endpoin that respond to any routes
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /pruebas
          method: POST
          cors: true
          documentation:
            summary: "Testing purposes, returns the body of the method"
            requestBody:
                description: "Any json file will work"
      - http:
          path: /peticiones
          method: POST
          cors: true
          documentation:
            summary: "Adds a new peticion to the list of existing peticiones"
            requestBody:
                description: "It asks for resources and has the hospital id"
            pathParams:
                -
                    name: x-api-key
                    required: true
                    description: "API Key identifier"
            requestModels:
                "application/json": "peticion"
            methodResponses:
                -
                    statusCode: "200"
                    responseBody:
                            description: "La peticion se agrego correctamente"
      - http:
          path: /peticiones
          method: GET
          cors: true
          documentation:
            summary: "Gets a list of all the existing peticiones"
            requestBody:
                description: "Empty request body"
            pathParams:
                -
                    name: x-api-key
                    required: true
                    description: "API Key identifier"
      - http:
          path: /login
          method: POST
          cors: true
      - http:
          path: /register
          method: POST
          cors: true
      - http:
          path: /CentrosHospitalarios
          method: POST
          cors: true
      - http:
          path: /CentrosHospitalarios
          method: GET
          cors: true
      - http:
          path: /envios
          method: GET
          cors: true
      - http:
          path: /envios
          method: POST
          cors: true
custom:
    documentation:
        version: '1'
        summary: 'API FAKE del Ministerio de Salud del Chaco'
        description: 'API para recibir peticiones y para manejo interno del grupo ministerio de salud. Esto es un trabajo practico de la universidad, no es una api real de ministerio.'
        resources: 
            -
                path: "peticiones"
                description: "Path used to see peticiones and add more"
        models:
            -
                name: doctor
                contentType: "application/json"
                schema:
                    type: object
                    properties: 
                        cantidad:
                            type: number
                        especialidad: 
                            type: string
            -
                name: envio
                contentType: "application/json"
                schema:
                    type: object
                    properties:
                        Envio:
                            type: object
                            properties:
                                idCentro:
                                    type: number
                                    required: true
                                idPeticion:
                                    type: number
                                    required: false
                                camillas: 
                                    type: number
                                jabonLitros:
                                    type: number
                                alcoholLitros: 
                                    type: number
                                barbijos:
                                    type: number
                                jeringas:
                                    type: number
                                cofias:
                                    type: number
                                medicos:
                                    type: array
                                    items:
                                        $ref: "{{model:doctor}}"
            -
                name: peticion
                contentType: "application/json"
                schema:
                    type: object
                    properties:
                        Peticion:
                            type: object
                            required:
                            - "idCentro"    
                            properties:
                                idCentro:
                                    type: number
                                camillas: 
                                    type: number
                                jabonLitros:
                                    type: number
                                alcoholLitros: 
                                    type: number
                                barbijos:
                                    type: number
                                jeringas:
                                    type: number
                                cofias:
                                    type: number
                                medicos:
                                    type: array
                                    items:
                                        $ref: "{{model:doctor}}"
                                respondidaCompletamente:
                                    type: boolean
                                rechazada: 
                                    type: boolean                                     
                                
                            



plugins:
  - serverless-aws-documentation 